# Generated by Django 4.1.1 on 2022-09-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.CharField(max_length=10)),
                ('following', models.CharField(max_length=10)),
                ('repos', models.CharField(max_length=10)),
                ('stars', models.CharField(max_length=10)),
                ('contrb', models.CharField(max_length=10)),
            ],
        ),
    ]
