# Generated by Django 4.1.1 on 2022-09-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_alter_github_contrb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='followers',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='github',
            name='following',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='github',
            name='repos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='github',
            name='stars',
            field=models.CharField(max_length=100),
        ),
    ]
