# Generated by Django 4.1.1 on 2022-09-24 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_alter_github_followers_alter_github_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
